[package]
name = "dav1d-sys"
version = "0.7.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
description = "FFI bindings to dav1d"
repository = "https://github.com/rust-av/dav1d-rs"
edition = "2021"

build = "build.rs"

[dependencies]
libc = "0.2"
